---
title: "Final Project"
author: "Donovan Doyle"
date: "October 17, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# loading libraries here, same old stuff.
library(tidyverse)
library(dplyr)
library(knitr)
library(kableExtra)
library(readxl)
library(stringr)

#reading in our csv. This came from Kaggle, and seems accurate but is a bit messy.
spreads1 <- read_csv("spreadspoke_scores.csv")
```



```{r, echo = FALSE, include = FALSE}
#Here we're starting to tidy the data. This process takes much longer than I anticipated. The data was pretty messy for what I was trying to do with it. Fortunately, this class prepared me well!
spreads_match <- spreads1 %>%
 #These are only subjects I'm interested in
   select(schedule_season, team_home, team_away, team_favorite_id, spread_favorite, score_home, score_away, schedule_playoff, weather_temperature) %>%
  #Filtering out data we can't really use
  filter(!is.na(spread_favorite)) %>%
  filter(schedule_playoff == "FALSE") %>%
  filter(schedule_season != 2018) %>%
  filter(schedule_season != 1978) %>%
  #We need the team names to fit the favorite ID. This is the only way for me to match and group_by.
  mutate(team_home = recode(team_home, "Tampa Bay Buccaneers" = "TB", "Arizona Cardinals" = "ARI", "Atlanta Falcons" = "ATL", "Baltimore Colts" = "IND", "Baltimore Ravens" = "BAL", "Buffalo Bills" = "BUF", "Carolina Panthers" = "CAR", "Chicago Bears" = "CHI", "Cincinnati Bengals" = "CIN", "Cleveland Browns" = "CLE", "Dallas Cowboys" = "DAL", "Denver Broncos" = "DEN", "Detroit Lions" = "DET", "Green Bay Packers" = "GB", "Houston Oilers" = "TEN", "Houston Texans" = "HOU", "Indianapolis Colts" = "IND", "Jacksonville Jaguars" = "JAX", "Kansas City Chiefs" = "KC", "Los Angeles Chargers" = "LAC", "Los Angeles Raiders" = "OAK", "Los Angeles Rams" = "LAR", "Miami Dolphins" = "MIA", "Minnesota Vikings" = "MIN", "New England Patriots" = "NE", "New Orleans Saints" = "NO", "New York Giants" = "NYG", "New York Jets" = "NYJ", "Oakland Raiders" = "OAK", "Philadelphia Eagles" = "PHI", "Phoenix Cardinals" = "ARI", "Pittsburgh Steelers" = "PIT", "San Diego Chargers" = "LAC", "San Francisco 49ers" = "SF", "Seattle Seahawks" = "SEA", "St. Louis Cardinals" = "ARI", "St. Louis Rams" = "LAR", "Tennessee Oilers" = "TEN", "Tennessee Titans" = "TEN", "Washington Redskins" = "WAS", .default = NULL)) %>%
  mutate(team_away = recode(team_away, "Tampa Bay Buccaneers" = "TB", "Arizona Cardinals" = "ARI", "Atlanta Falcons" = "ATL", "Baltimore Colts" = "IND", "Baltimore Ravens" = "BAL", "Buffalo Bills" = "BUF", "Carolina Panthers" = "CAR", "Chicago Bears" = "CHI", "Cincinnati Bengals" = "CIN", "Cleveland Browns" = "CLE", "Dallas Cowboys" = "DAL", "Denver Broncos" = "DEN", "Detroit Lions" = "DET", "Green Bay Packers" = "GB", "Houston Oilers" = "TEN", "Houston Texans" = "HOU", "Indianapolis Colts" = "IND", "Jacksonville Jaguars" = "JAX", "Kansas City Chiefs" = "KC", "Los Angeles Chargers" = "LAC", "Los Angeles Raiders" = "OAK", "Los Angeles Rams" = "LAR", "Miami Dolphins" = "MIA", "Minnesota Vikings" = "MIN", "New England Patriots" = "NE", "New Orleans Saints" = "NO", "New York Giants" = "NYG", "New York Jets" = "NYJ", "Oakland Raiders" = "OAK", "Philadelphia Eagles" = "PHI", "Phoenix Cardinals" = "ARI", "Pittsburgh Steelers" = "PIT", "San Diego Chargers" = "LAC", "San Francisco 49ers" = "SF", "Seattle Seahawks" = "SEA", "St. Louis Cardinals" = "ARI", "St. Louis Rams" = "LAR", "Tennessee Oilers" = "TEN", "Tennessee Titans" = "TEN", "Washington Redskins" = "WAS", .default = NULL)) %>%
  #I don't want it as factors I think, so we'll make them characters
  mutate(team_home = parse_character(team_home)) %>%
  mutate(team_away = parse_character(team_away)) %>%
  mutate(team_favorite_id = parse_character(team_favorite_id))
  
spreads_home_favorites <- spreads_match %>%
  #Instead of using if/then's in mutates to make the data usable, I just tried dividing up the frames then joining them again
  filter(team_home == team_favorite_id) %>%
  rename(year = schedule_season, fav_team = team_home, under_team = team_away, home_team = team_favorite_id, spread = spread_favorite, fav_score = score_home, under_score = score_away, playoff = schedule_playoff, temp = weather_temperature) %>%
  mutate(home_fav = TRUE) %>%
  select(-home_team)

#Continued on what I did in above section, just for away teams
spreads_away_favorites <- spreads_match %>%
  filter(team_away == team_favorite_id) %>%
  rename(year = schedule_season, fav_team = team_away, under_team = team_home, away_team = team_favorite_id, spread = spread_favorite, fav_score = score_away, under_score = score_home, playoff = schedule_playoff, temp = weather_temperature) %>%
  mutate(home_fav = FALSE) %>%
  select(-away_team)


#Adding an important topic: did they cover?
spreads_comb_under <- full_join(spreads_home_favorites, spreads_away_favorites, .id = "source") %>%
  mutate(diff = under_score - fav_score) %>%
  filter(diff > spread) %>%
  mutate(fav_cover = FALSE) %>%
  mutate(spread_win = under_team)
  
#Expanding on what I did above. This is the last part of digging out how teams covered, as this wasn't given in the original data set at all.
spreads_comb_fav <- full_join(spreads_home_favorites, spreads_away_favorites, .id = "source") %>%
  mutate(diff = under_score - fav_score) %>%
  filter(diff < spread) %>%
  mutate(fav_cover = TRUE) %>%
  mutate(spread_win = fav_team)

#The final join. My data is ready!
spreads_tidy <- full_join(spreads_comb_fav, spreads_comb_under, .id = "source")
```

```{r plots, echo = FALSE, message = FALSE}
#This is building out how teams performed when they were favorites and if they covered or not.
spreads_team_fav_summary <- spreads_tidy %>%
  group_by(fav_team) %>%
  mutate(avg_diff = mean(diff)) %>%
  mutate(fav_cover = as.numeric(fav_cover)) %>%
  mutate(likely_fav_cover = sum(fav_cover) / n())

#Doing the same thing as above, but with when teams were underdogs.
spreads_team_under_summary <- spreads_tidy %>%
  group_by(under_team) %>%
  mutate(avg_diff = mean(diff)) %>%
  mutate(fav_cover = as.numeric(fav_cover)) %>%
  mutate(likely_under_cover = sum(fav_cover) / n())
  
#This is the first part of my table analysis, finding how teams perform when they're underdogs. I think a lot of the explanation behind this would have to do with team culture, which changes over time so I can't prove anything, but it is still an interesting experiment to witness it play out.
spreads_when_under <- spreads_tidy %>%
  group_by(under_team) %>%
  mutate(avg_diff = mean(diff)) %>%
  mutate(fav_cover = as.numeric(fav_cover)) %>%
  mutate(likely_under_cover = sum(fav_cover) / n()) %>%
  select(under_team, likely_under_cover) %>%
  distinct(under_team, likely_under_cover) %>%
  filter(!is.na(likely_under_cover)) %>%
  arrange(under_team) %>%
  mutate(bet_against = round((1 - likely_under_cover)*18.70, 2)) %>%
  mutate(likely_under_cover = round(likely_under_cover*18.70, 2)) %>%
  rename(Team = under_team, 'Betting on Expected Payout' = likely_under_cover, 'Betting Against Expected Payout' = bet_against)

#This is building my second table. I wanted to divide up my data by favorites and underdogs because it would create more robust analysis and help work out lags in the data. For example, the Patriots were likely favorites in every single game they played in 2007. I'm more interested in how they were able to perform against those expectations, compared with when they were mediocre in the 80s and weighting that equally to their 2007 dominance. The part that makes my analysis substantial is factoring in the house's cut. It would be easy for anybody to find a rule that worked 50% of the time, but to find a rule that will make money in practice is much more valuable.
spreads_team_summary <- 
  full_join(spreads_team_fav_summary, spreads_team_under_summary) %>%
  select(fav_team, likely_fav_cover) %>%
  distinct(fav_team, likely_fav_cover) %>%
  filter(!is.na(likely_fav_cover)) %>%
  rename(team = fav_team, likely_fav_cover = likely_fav_cover) %>%
  arrange(team) %>%
  mutate(bet_against = round((1 - likely_fav_cover) * 18.70, 2)) %>%
  mutate(likely_fav_cover = round(likely_fav_cover*18.70, 2)) %>%
  rename(Team = team, 'Betting on Expected Payout' = likely_fav_cover, 'Betting against Expected Payout' = bet_against)
```

```{r, include = FALSE}
#writing my RDS files. Done!
write_rds(spreads_when_under, path = "Recreating_Kane/spreads_when_under.rds")
write_rds(spreads_team_summary, path = "Recreating_Kane/spreads_team_summary.rds")
```

